### ISSUE TITLE
use long flags when scripting

### ISSUE THREAD

**Issue by LucasLarson** [LucasLarson/git-default-branch#21]
Almost a decade ago, @adamyonk of shell lore, implored us to “[u]se long flags when scripting”.[^1] This means that even instances of `set -x`  could appear as `set -o xtrace`.[^2]

https://github.com/LucasLarson/git-default-branch/blob/007a68ea6e09d2c806fdadb60dbf99eda6652200/bin/git-default-branch#L12
https://github.com/LucasLarson/git-default-branch/blob/007a68ea6e09d2c806fdadb60dbf99eda6652200/bin/git-default-branch#L48-L49

[^1]: [`adamyonk.com/posts/2012/12/17/use-long-flags-when-scripting`](https://web.archive.org/web/20130809202544id_/adamyonk.com/posts/2012/12/17/use-long-flags-when-scripting.html)
[^2]: [`opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html` § Description](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_25_03)

**Comment by adamyonk** [comment]
❤️
